config/routes.rb
Rails.application.routes.draw do
  root to: "posts#index"
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, controllers: { registrations: "users/registrations" }
  resources :users, only: [:show]
  resources :posts
  resources :relationships
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates_presence_of :user_id, :content

  belongs_to :user

  after_create :check_mentions

  def check_mentions
    user = User.basic_search(self.content).first
    if user
      UserMailer.mention(user).deliver
    end
  end
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base

  validates_presence_of :follower_id
  validates_presence_of :followed_id

  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

  after_create :send_spotted_message

  def send_spotted_message
    @user = User.find(self.followed_id)
    UserMailer.spotted(@user).deliver
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  after_create :send_welcome_message

  validates_presence_of :name

  has_many :posts, dependent: :destroy
  has_many :relationships, foreign_key: "follower_id", dependent: :destroy
  has_many :followed_users, through: :relationships, source: :followed
  has_many :reverse_relationships, foreign_key: "followed_id",
                                   class_name:  "Relationship",
                                   dependent:   :destroy
  has_many :followers, through: :reverse_relationships, source: :follower

  def send_welcome_message
    UserMailer.signup_confirmation(self).deliver
  end

  def following? user
    relationships.find_by_followed_id(user.id)
  end

  def follow user
    self.relationships.create(followed_id: user.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      respond_to do |format|
        format.html { redirect_to posts_url }
        format.js
      end
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update(params[:post])
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.js
    end
  end

private

  def post_params
    params.require(:post).permit(:content).merge(user_id: current_user.id)
  end

end

app/controllers/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

  before_filter :configure_permitted_parameters

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) do |u|
      u.permit(:name, :email, :password, :password_confirmation)
    end
    devise_parameter_sanitizer.for(:account_update) do |u|
      u.permit(:name, :email, :password, :password_confirmation, :current_password)
    end
  end

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    @user = User.find(params[:relationship][:followed_id])
    @relationship = Relationship.new(relationship_params)
    if @relationship.save
      respond_to do |format|
        format.html { redirect_to @user }
        format.js
      end
    end
  end

private

  def relationship_params
    params.require(:relationship).permit(:followed_id).merge(follower_id: current_user.id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @relationship = Relationship.new
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
  <% object.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twister</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
        <ul class="nav navbar-nav">
          <li><a href="/" class="navbar-brand">Twister</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li><%= link_to "#{current_user.name}", edit_user_registration_path %></li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "Sign up", new_user_registration_path %></li>
            <li><%= link_to "Login", new_user_session_path %></li>
          <% end %>
        </ul>
    </div>
  </nav>

  <div class="container-fluid">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <%= yield %>
      </div>
    </div>
  </div>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post, html: {class: "form"}, remote: true do |f| %>
  <%= render 'layouts/errors', :object => @post %>

  <div class="form-group">
    <%= f.text_field :content, class: "form-control" %>
  </div>

  <%= f.submit "Twist it up!", class: "btn btn-success" %>
<% end %>

app/views/posts/_post.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <p><%= link_to "#{post.content}", post_path(post) %></p>
    <p>Twisted by <%= link_to "#{post.user.name}", post.user %></p>
  </div>
</div>

app/views/posts/create.js.erb
$('#new_post').remove();
$('#new_post_link').show();
$('#posts_list').append('<%= j render(@post) %>');

app/views/posts/index.html.erb
<%= link_to "New Twist", new_post_path, id: "new_post_link", class: "btn btn-lg btn-primary", remote: true %>
<br><br>
<div id="posts_list">
<%= render @posts %>
</div>

app/views/posts/new.js.erb
$('#new_post_link').hide().after('<%= j render("form") %>');

app/views/posts/show.html.erb
<h1><%= @post.content %></h1>
<p>Twisted by <%= link_to @post.user.name %></p>

app/views/relationships/_form.html.erb
<%= form_for @relationship, remote: true do |f| %>
  <%= f.hidden_field :followed_id, :value => @user.id %>
  <%= f.submit "Follow", class: "btn btn-success" %>
<% end %>

app/views/relationships/create.js.erb
$('#follower-count').text('<%= @user.followers.count %>');

app/views/users/show.html.erb
<h1><%= @user.name %></h1>

<%= render 'relationships/form' %>

<h3>Followers: <span id="follower-count"><%= @user.followers.count %></span></h3>
<br>
<br>
<%= render @user.posts %>